/*
Primitve Data Types
1. Numbers - int, floats
2. strings '' "" ``
3. booleans t or f
4. null - empty or no val
5. undefined - var declared with no val
6. Symbol - unique val generated by symbol consturctor
*/
/*
non-primitve data types
1. Objects
2. Arrays
*/
// primitive-  immutable (non-modifiable)
let One =1, Two =2, three =1
console.log(One == three) //true
console.log(One == Two) //false

let arr = [1,2,3]
arr[2] = 12
console.log(arr)

let arr2 = [2,3,32]
let arr3 = [2,3,32]
console.log(arr2 == arr3) //false

let u1 ={
    name:'Aero',
    role:'student',
    country:'India'
}

let u2 ={
    name:'Aero',
    role:'student',
    country:'India'
}
console.log(u1 == u2) //false

//do not compare non-primmitve types
// do not compare arrays, funcitons, objects
// non-primitve data types aka reference types, as they're compared by referece instead of value

